name: Create Release
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Loading Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Installing catalyst
        run: npm i -g zcatalyst-cli
      - name: Installing Packages for 'Node'
        run: cd functions/Node/ && npm install --omit=dev
      - name: Deploying code to catalyst
        run: catalyst deploy --project ${{ secrets.CATALYST_PROJECT_NAME}} --org ${{ secrets.CATALYST_ORG}} --token ${{ secrets.CATALYST_TOKEN}}
