name: Create Release
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Loading Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Installing catalyst
        run: npm i -g zcatalyst-cli
      - name: Installing Packages for 'Node'
        run: cd functions/Node/ && npm install --omit=dev
      - name: Deploying code to catalyst
        run: catalyst deploy --project ${{ TESTSECRET.Aliencity}} --org ${{ TESTSECRET.832316553}} --token ${{ TESTSECRET.m_1004.8514e429fe1f4242fbd2ce97b681c16a.4d38872ef0b87a1483b06351a525ccca}}
